version: '3.6'


# Backend API
services: 
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_USER: bill
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    links:
      - postgres
    ports: 
      - "3000:3000"  
    volumes:
      - ./:/usr/src/smart-brain-api
      - ./pgdata:/var/lib/postgresql/data
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bill
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports: 
      - "5432:5432"